/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./duck.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/duck.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.466}>
        <group position={[0, 0, 0.625]} rotation={[0, 0, -0.635]}>
          <mesh geometry={nodes.Roundcube_0.geometry} material={nodes.Roundcube_0.material} />
          <mesh geometry={nodes.Roundcube_1.geometry} material={nodes.Roundcube_1.material} />
          <mesh geometry={nodes.Roundcube_2.geometry} material={nodes.Roundcube_2.material} />
          <mesh geometry={nodes.Roundcube_3.geometry} material={nodes.Roundcube_3.material} />
          <mesh geometry={nodes.Roundcube_4.geometry} material={nodes.Roundcube_4.material} />
        </group>
        <group position={[-1.5, -1.603, 0.456]} rotation={[-0.135, -0.252, -0.5]}>
          <mesh geometry={nodes.Frog_Body_0.geometry} material={nodes.Frog_Body_0.material} />
          <mesh geometry={nodes.Frog_Body_1.geometry} material={nodes.Frog_Body_1.material} />
          <mesh geometry={nodes.Frog_Body_2.geometry} material={nodes.Frog_Body_2.material} />
          <mesh geometry={nodes.Frog_Body_3.geometry} material={nodes.Frog_Body_3.material} />
          <mesh geometry={nodes.Frog_Body_4.geometry} material={nodes.Frog_Body_4.material} />
          <mesh geometry={nodes.Frog_Body_5.geometry} material={nodes.Frog_Body_5.material} />
        </group>
        <group position={[-1.805, -0.409, -4.583]} rotation={[-Math.PI / 2, 1.433, Math.PI / 2]}>
          <mesh geometry={nodes.Circle007_0.geometry} material={nodes.Circle007_0.material} />
          <mesh geometry={nodes.Circle007_0_1.geometry} material={nodes.Circle007_0_1.material} />
        </group>
        <group position={[0, 0, -1.185]} rotation={[0, 0, -0.635]}>
          <mesh geometry={nodes.Roundcube001_0.geometry} material={nodes.Roundcube001_0.material} />
          <mesh geometry={nodes.Roundcube001_1.geometry} material={nodes.Roundcube001_1.material} />
          <mesh geometry={nodes.Roundcube001_2.geometry} material={nodes.Roundcube001_2.material} />
          <mesh geometry={nodes.Roundcube001_3.geometry} material={nodes.Roundcube001_3.material} />
          <mesh geometry={nodes.Roundcube001_4.geometry} material={nodes.Roundcube001_4.material} />
        </group>
        <mesh geometry={nodes.Plane_0.geometry} material={nodes.Plane_0.material} />
        <mesh geometry={nodes.Plane001_0.geometry} material={nodes.Plane001_0.material} position={[0, 0, -2.033]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Vert_0.geometry} material={nodes.Vert_0.material} position={[-1.621, -1.661, 0.632]} />
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/duck.glb')